language: objective-c
before_install:
    - gem install cocoapods
    - brew update
script: xctool -workspace CrashManager.xcworkspace -scheme CrashManager

branches:
  only:
    - master
    - develop