language: objective-c
before_install:
    - gem install cocoapods
    - brew update
    - brew upgrade xctool
script: xctool -workspace CrashManager.xcworkspace -scheme CrashManager

branches:
  only:
    - master
    - develop